# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f941b4fca2b905aa5c6e88582117b9c41f67cd2d6210d1ea14e9069e8973c15ec844aa15408bf5b9130059f10c7d8d2a8cc947065ab636b41eb6722f9ddc7a5b

test:
  secret_key_base: c2c6868863e56f55e29ae1b1b934c7b66fb4bb22cc46ac45a621ea614a33281ac1d36ebf593def70d051d85e798b9a58c877ef0bd250270b442ffc7444d0ef0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
